# Generated by Django 4.1.7 on 2023-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('green', 'Green')], default='', max_length=20),
        ),
    ]
