# Generated by Django 4.1.7 on 2023-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_settings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('green', 'Green'), ('dark', 'Dark Default')], default='', max_length=20),
        ),
    ]
