# Generated by Django 4.1.7 on 2023-03-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('source', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUploadKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.project')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.project')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageRawDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_detail', models.JSONField(default=dict)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.coveragesummary')),
            ],
        ),
    ]
