# Generated by Django 4.1.7 on 2023-03-07 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_projectaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadkey',
            name='setup_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
