# Generated by Django 4.1.7 on 2023-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_projectuploadkey_setup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragesummary',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
