# Generated by Django 4.1.7 on 2023-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_projectuploadkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragesummary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
