# Generated by Django 4.1.7 on 2023-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_coveragesummary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('python-coveragepy', 'Python (Coverage.py)'), ('python-pytest', 'Python (Pytest)'), ('javascript-jest', 'JavaScript (Jest) (Coming soon)')], default='python-coveragepy', max_length=30),
            preserve_default=False,
        ),
    ]
