# Generated by Django 4.1.7 on 2023-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_project_creator_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragerawdetail',
            name='folder_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
