# Generated by Django 4.1.7 on 2023-03-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_coveragerawdetail_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('python-coveragepy', 'Python (Coverage.py)'), ('javascript-istanbul', 'JavaScript (Istanbul)')], max_length=30),
        ),
    ]
