# Generated by Django 4.1.7 on 2023-03-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('python-coveragepy', 'Python (Coverage.py)'), ('nodejs-istanbul', 'Node.js (Istanbul)')], max_length=30),
        ),
    ]
